version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: scouts_rag_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: scouts_rag_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - scouts_rag_network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: scouts_rag_backend
    restart: unless-stopped
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=scouts_rag_db
      - CORS_ORIGINS=*
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
    networks:
      - scouts_rag_network
    # Connect to host network to access external Qdrant and Ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # Frontend Web App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: scouts_rag_frontend
    restart: unless-stopped
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - scouts_rag_network

  # Optional: Nginx reverse proxy (for production)
  nginx:
    image: nginx:alpine
    container_name: scouts_rag_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - scouts_rag_network
    profiles:
      - production

volumes:
  mongodb_data:

networks:
  scouts_rag_network:
    driver: bridge